### PR TITLE
added zf3 compatibility; removed zf2 compatibility

### PR DESCRIPTION
**Pull request by koseduhemak**
just added zf3 compatibility via pull request.
Maybe you can introduce a new branch 3.x so we can keep zf2 compatibility in the 2.x branch.

### CODE REVIEW

**Comment by rodmcnew** [comment]
We don't really maintain this project anymore. But if its helpful to you, I'm willing to merge and tag this as a new major version. 

- composer.json needs to be modified to ensure this won't be trying to install on ZF 2.* where the ContainerInterface may not work
- travis.yml needs to be modified so the build doesn't break on the new php version you put in

**Comment by rodmcnew** [comment]
This has been merged and tagged as version 3.0.0

**Comment by koseduhemak** [comment]
thank you for supporting me :) 
I did not find a proper replacement yet - could you recommend another module which has same functionality (file browsing, file uploading, easy selection of files stored in specific folders and link them to an database entity / input field in a form f.e.)?

**Comment by rodmcnew** [comment]
No problem. I'm not aware of a replacement module but haven't looked either. We replaced zf2-elfinder in our own stack with the following package. It only works with Amazon S3 and I don't think it does file uploads. https://github.com/awslabs/aws-js-s3-explorer

We would maintain zf2-elfinder more but its hard to mess with it because we switched from Zend-MVC to Zend-Expressive. Not only do we not use the package, we don't even use the framework it's for.

**Comment by koseduhemak** [comment]
Thank you for your answer. I encounter many people switching from "legacy" zend to zend expressive... I think I need to have a look at expressive :)

One thing:
I think you accidentally tagged the old master (without the new commits) as 3.0.0.

**Comment by rodmcnew** [comment]
I cloned and tagged it after merging but it looks like the clone gave me an older version due to caching.

Fixed in v3.0.1

**Comment by koseduhemak** [comment]
Thank you very much. Everything is working now.

**Pull request merged**
