### PR TITLE
Fixes loading of assets and adds new config service for complex configurations.  No BC breaks

### PR DESCRIPTION
**Pull request by wshafer**
Fixed BC Break from upstream.
Added new config service for more complex mount configs.

### CODE REVIEW

**Comment by wshafer** [comment]
Please create tag 2.0.2 for this release.

Thanks

**Comment by rodmcnew** [comment]
build broken

**Comment by wshafer** [comment]
@rodmcnew - Fixed!  :+1:

**Comment by wshafer** [comment]
@rodmcnew @jerv13 - Sorry to bug you guys with this one, but v2.0.1 is completely broken.  This fixes those issues.

**Comment by rodmcnew** [comment]
tagged 2.0.2

**Pull request merged**
